language: python

python:
  - "2.7.15"

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - make build

script:
  - make test

notifications:
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false
